services:
  vllm-qwen30b:
    image: quay.nju.edu.cn/ascend/vllm-ascend:v0.9.1
    container_name: vllm-qwen30b
    restart: unless-stopped
    environment:
      - VLLM_USE_V1=1
      - PYTORCH_NPU_ALLOC_CONF=max_split_size_mb:256
      - VLLM_USE_MODELSCOPE=True
      - ASCEND_VISIBLE_DEVICES=0,1,2,3
    ports:
      - "9000:8000"
    volumes:
      - /usr/local/dcmi:/usr/local/dcmi
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
      - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      - /etc/ascend_install.info:/etc/ascend_install.info
      - /root/.cache:/root/.cache
    devices:
      - /dev/davinci0:/dev/davinci0
      - /dev/davinci1:/dev/davinci1
      - /dev/davinci2:/dev/davinci2
      - /dev/davinci3:/dev/davinci3
      - /dev/davinci_manager:/dev/davinci_manager
      - /dev/devmm_svm:/dev/devmm_svm
      - /dev/hisi_hdc:/dev/hisi_hdc
    command:
      - bash
      - -lc
      - |
        vllm serve Qwen/Qwen3-30B-A3B \
          --host 0.0.0.0 \
          --port 8000 \
          --tensor-parallel-size 4 \
          --gpu-memory-utilization 0.9 \
          --max-num-seqs 16 \
          --max-num-batched-tokens 4096 \
          --served-model-name Qwen/Qwen3-30B-A3B \
          --additional-config '{"ascend_scheduler_config":{"enabled":true,"enable_chunked_prefill":true}}'

  vllm-qwen8b:
    image: quay.nju.edu.cn/ascend/vllm-ascend:v0.9.1
    container_name: vllm-qwen8b
    restart: unless-stopped
    environment:
      - VLLM_USE_V1=1
      - PYTORCH_NPU_ALLOC_CONF=max_split_size_mb:256
      - VLLM_USE_MODELSCOPE=True
      - ASCEND_VISIBLE_DEVICES=4
    ports:
      - "9001:8001"
    volumes:
      - /usr/local/dcmi:/usr/local/dcmi
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
      - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      - /etc/ascend_install.info:/etc/ascend_install.info
      - /root/.cache:/root/.cache
    devices:
      - /dev/davinci4:/dev/davinci4
      - /dev/davinci_manager:/dev/davinci_manager
      - /dev/devmm_svm:/dev/devmm_svm
      - /dev/hisi_hdc:/dev/hisi_hdc
    command:
      - bash
      - -lc
      - |
        vllm serve Qwen/Qwen3-8B \
          --host 0.0.0.0 \
          --port 8001 \
          --tensor-parallel-size 1 \
          --gpu-memory-utilization 0.9 \
          --max-num-seqs 32 \
          --max-num-batched-tokens 8192 \
          --served-model-name Qwen/Qwen3-8B \
          --additional-config '{"ascend_scheduler_config":{"enabled":true,"enable_chunked_prefill":true}}'
